### ISSUE TITLE
The rule from Base filter does not work

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/SafariConverterLib#22]
@Alex-302 commented on [Tue Jul 06 2021](https://github.com/AdguardTeam/AdGuardForSafari/issues/632)

URL: 
https://exey.io/q9Ad

Screenshot:
![image](https://user-images.githubusercontent.com/8361299/124520233-7df68a00-ddf4-11eb-8ca1-02bd05507a06.png)

The rule, which does not applied when Base filter is enabled
`@@||googletagmanager.com/gtag/js$domain=linkpoi.me|bevru.club|arurio.club|exey.io|eririo.club|freshi.site|cookuve.com|srek.net|exe.app`

It works, when added to user rules.

Similar issue:
https://github.com/AdguardTeam/AdGuardForSafari/issues/511

**Comment by Alex-302** [comment]
Similar issue:
<details>

https://github.com/AdguardTeam/AdGuardForSafari/issues/511

The rule below (from annoyances) doesn't work in AG for Safari and AG for iOS.
`@@||adservice.google.*/adsid/integrator.js$~script,domain=muyhistoria.es|marie-claire.es|miarevista.es|muynegociosyeconomia.es|serpadres.es|muyinteresante.es`

But it exists in optimized filters and works from the user rules.

Related issue: https://github.com/AdguardTeam/AdguardFilters/issues/71388

Same here https://github.com/AdguardTeam/AdguardFilters/issues/71879 
with rule `@@||pakkotoisto.com/js/siropu/am/ads.min.js$domain=pakkotoisto.com`

And here https://github.com/AdguardTeam/AdguardFilters/issues/71234
`@@||aktuality.sk^$generichide`

[adg_safari_logs_1610993497550.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5831886/adg_safari_logs_1610993497550.zip)


</details>

**Comment by tvinzz** [comment]
this exception rule and rule to be excepted are compiled in different extensions, so need to add affinity directive

**Comment by Alex-302** [comment]
The first issue resolved. Not a bug, just `affinity` directive is required.
