### ISSUE TITLE
The rule doesn't work

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/SafariConverterLib#24]
`@@||tpc.googlesyndication.com/safeframe/*/html/container.html$domain=serpadres.es` from the Spanish filter doesn't work
(works only from user rules)

https://github.com/AdguardTeam/AdguardFilters/issues/90442

![Screenshot 2021-08-17 at 13 41 53](https://user-images.githubusercontent.com/18536328/129713367-dbe7f9f5-c3a6-4c1a-add0-2f1cbb397cc4.png)
![Screenshot 2021-08-17 at 13 40 00](https://user-images.githubusercontent.com/18536328/129713384-7e04b421-fb14-4fb3-bf5d-ee2763812ebc.png)

**Comment by tvinzz** [comment]
fixed by updating filters.
feel free to open if reproduce again.
