### ISSUE TITLE
Spotify links can't be opened on iOS

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/SafariConverterLib#25]
@iDjay commented on [Wed Jun 23 2021](https://github.com/AdguardTeam/AdguardFilters/issues/86639)

**Issue**:
AdGuard incorrectly blocks Spotify links from opening on iOS (14.6).
**Steps to recreate**:
1. make sure to have NOT installed the Spotify app on your iPhone.
2. try to open a Spotify link on your iPhone, f.e. https://open.spotify.com/playlist/7vTUX5URUS4ntuIroEXtAv
**Behavior**: 
the website got blocked by AdGuard
**Expected Behavior**:
Safari should open the website
**Filters**:
basic filter; tracking protection; social media; annoyances (this may cause the issue); German

---

@Alex-302 commented on [Thu Jun 24 2021](https://github.com/AdguardTeam/AdguardFilters/issues/86639#issuecomment-867794289)

I don't have Spotify app, and I can't reproduce with your settings(also with AdGuard DNS).
I need screenshot.

---

@iDjay commented on [Fri Jun 25 2021](https://github.com/AdguardTeam/AdguardFilters/issues/86639#issuecomment-868507213)

Weird, I had this issue since months however it’s gone now. Why does this always happen when I report something 😂

Will do a screen recording next time as proof.

---

@iDjay commented on [Wed Jul 07 2021](https://github.com/AdguardTeam/AdguardFilters/issues/86639#issuecomment-875780369)

The issue is back @Alex-302 
![69D54C06-7931-4D71-9BE8-CF778B950A8F](https://user-images.githubusercontent.com/83946731/124801662-608e0100-df57-11eb-84a3-e789d407a5c9.png)

---

@Alex-302 commented on [Wed Jul 07 2021](https://github.com/AdguardTeam/AdguardFilters/issues/86639#issuecomment-875806087)

Need sample link.

---

@iDjay commented on [Wed Jul 07 2021](https://github.com/AdguardTeam/AdguardFilters/issues/86639#issuecomment-875808769)

Just any link leading to Spotify.
https://open.spotify.com/playlist/6S4pdwnUd2LcOyQvKJv3AA

---

@Alex-302 commented on [Thu Jul 08 2021](https://github.com/AdguardTeam/AdguardFilters/issues/86639#issuecomment-876577818)

Works fine on my end with DNS.
@AdguardTeam/filters-maintainers please take a look.

---

@iDjay commented on [Thu Jul 08 2021](https://github.com/AdguardTeam/AdguardFilters/issues/86639#issuecomment-876638437)

Yes for some reason it‘s working fine now again, but it didn‘t work for months until I decided to turn off AdGuard to open the page once. That did the trick.
Also it seems like that only shared Spotify links have this issue, f.e. If someone sends you the link in iMessage. Normally iOS would redirect to the AppStore/ launch Spotify to open the link within the app.

---

@iDjay commented on [Thu Jul 08 2021](https://github.com/AdguardTeam/AdguardFilters/issues/86639#issuecomment-876640047)

That’s the exact url which redirects to the Spotify app:
https://app.adjust.net.in/abuwqb?tracker_limit=250000&deep_link=spotify%3A%2F%2Fplaylist%2F6xGLprv9fmlMgeAMpW0x51%3Fsi%3Dy_YdGXqvQvWQa9AF0bvStg&redirect=http%3A%2F%2Fopen.spotify.com%2Fplaylist%2F6xGLprv9fmlMgeAMpW0x51%3Fsi%3Dy_YdGXqvQvWQa9AF0bvStg%26nd%3D1&label=sp_cid%3A1a193ca74f9e53dbd733faa234cba5e1

---

@Alex-302 commented on [Tue Jul 13 2021](https://github.com/AdguardTeam/AdguardFilters/issues/86639#issuecomment-878936782)

Which filter blocks it(disable one by one with checking)?

---

@iDjay commented on [Tue Jul 13 2021](https://github.com/AdguardTeam/AdguardFilters/issues/86639#issuecomment-879007080)

@Alex-302 AdGuard Privacy Protection

---

@Alex-302 commented on [Fri Jul 16 2021](https://github.com/AdguardTeam/AdguardFilters/issues/86639#issuecomment-881558795)

@iDjay Please test
`@@||app.adjust.net.in/*&redirect=redirect=http%3A%2F%2Fopen.spotify.com%2Fplaylist`

---

@iDjay commented on [Fri Jul 16 2021](https://github.com/AdguardTeam/AdguardFilters/issues/86639#issuecomment-881658829)

Doesn‘t seem to work with the link above.

---

@Alex-302 commented on [Wed Jul 21 2021](https://github.com/AdguardTeam/AdguardFilters/issues/86639#issuecomment-884294237)

try
`@@||app.adjust.net.in/*&redirect=redirect=*open.spotify.com`

---

@iDjay commented on [Thu Jul 22 2021](https://github.com/AdguardTeam/AdguardFilters/issues/86639#issuecomment-884738770)

Nope :D 

---

@chirag127 commented on [Wed Aug 11 2021](https://github.com/AdguardTeam/AdguardFilters/issues/86639#issuecomment-896716043)

> The issue is back @Alex-302
> ![69D54C06-7931-4D71-9BE8-CF778B950A8F](https://user-images.githubusercontent.com/83946731/124801662-608e0100-df57-11eb-84a3-e789d407a5c9.png)

what is written in the photo?

---

@iDjay commented on [Wed Aug 11 2021](https://github.com/AdguardTeam/AdguardFilters/issues/86639#issuecomment-896809178)

Safari can't open the webpage.
Error: Page is blocked by an AdBlocker.

---

@Alex-302 commented on [Tue Aug 17 2021](https://github.com/AdguardTeam/AdguardFilters/issues/86639#issuecomment-896809354)

URL is blocked by content blocker

**Comment by iDjay** [comment]
![C5BD844A-E32A-4183-AF4D-E92258464F58](https://user-images.githubusercontent.com/83946731/130320032-dcaf616a-2e85-4f06-a1cb-6e97576149d5.png)

still appearing 🤔
