### ISSUE TITLE
How to make rules work

### ISSUE THREAD

**Issue by JSBmanD** [AdguardTeam/SafariConverterLib#28]
When I generate rules and take it from rules then packing to json file it doesn't work (nothing is being blocked). What are the steps for making rules work?

**Comment by tvinzz** [comment]
@JSBmanD, you have to create content-blocker extension and add rules to it's json file as described here: https://developer.apple.com/documentation/safariservices/creating_a_content_blocker

**Comment by JSBmanD** [comment]
@tvinzz do you use any tools to format/delete invalid rules? I think they're not working because they're not properly formatted/have errors.

**Comment by tvinzz** [comment]
@JSBmanD, we use rules prepared by [FiltersCompiler](https://github.com/AdguardTeam/FiltersCompiler) lib with validator. Rules invalid for Safari browser are excluded during conversion.
Please, provide an example of rules you trying to use.

**Comment by Birbber** [comment]
@JSBmanD Any example?

**Comment by zzebrum** [comment]
reopen if needed
