### ISSUE TITLE
Do not split rules with many domains in the `unless-domain` and `if-domain`

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/SafariConverterLib#51]
`~example.org,.....,~example1000.org##banner` rule will be split into several rules in the resulting json. This is plain wrong.

Here's what we should do:

1. Check how many domains can in theory be specified in `unless-domains`
2. Discard rules that have more domains than that.

**Comment by Alex-302** [comment]
> 2\. Discard rules that have more domains than that.

How will the filters maintainers know about this?

**Comment by ameshkov** [comment]
The only way would be to have a special check in AGLint for this.

**Comment by Alex-302** [comment]
Maybe the apps that has problems with such rules should be warned about it - only AdGuard for iOS and Safari?
Other products are not affected by the problem.

**Comment by ameshkov** [comment]
There are lots of rules that are getting discarded when converting them for Safari, it's not realistic to list them all.

The problem with this particular case is that the problem can be not with a single rule, but with a multitude of `#@#` rules.

**Comment by Alex-302** [comment]
> it's not realistic to list them all

Can be printed to the log.

**Comment by ameshkov** [comment]
I actually think we're doing that when debug log is enabled

**Comment by Alex-302** [comment]
I can't find it

![image](https://github.com/AdguardTeam/SafariConverterLib/assets/8361299/3861ab5a-c1d3-4db7-98cc-6f41741dbedb)

**Comment by ameshkov** [comment]
Examine `com.adguard.AdguadExtension`

**Comment by Alex-302** [comment]
I don't see any rules there.

Why not use the obvious file names? Because of OS limitations?

![image](https://github.com/AdguardTeam/SafariConverterLib/assets/8361299/299c78c4-67f5-4203-b95b-130b91aa6c31)

**Comment by ameshkov** [comment]
Tbh, no idea:)

**Comment by Alex-302** [comment]
In any case, only the number of errors is logged, not the details.

![image](https://github.com/AdguardTeam/SafariConverterLib/assets/8361299/fbee216c-f3e6-4c65-887b-424adcd396d0)

**Comment by maximtop** [comment]
I've tested on macOS 13.4 and Safari 16.5, and it looks like "unless-domain" and "if-domain" support at least 10000 values.
