### ISSUE TITLE
Convert rules with Extended CSS to simple rules where they have a 1:1 counterpart

### ISSUE THREAD

**Issue by Cyberbeni** [AdguardTeam/SafariConverterLib#59]
For example hufilter has this rule with `-abp-has`: https://github.com/hufilter/hufilter/blob/aa8ccd520bf7a9d154fc3cb4cc945eab15254c53/hufilter-adguard.txt#L1208

Since `has` is available since iOS 16.4, we could convert this rule to `prohardver.hu###page-forum #center > div:has(h4 + [onclick*="https://prohardver.hu/muvelet/hozzaferes/kapcsolodas.php"])`, allowing it to function without asking the user to access all webpage content  (=turning on advanced protection).

**Comment by ameshkov** [comment]
That's on purpose, we provide a way to use JS engine instead of native implementation when a filter list maintainer needs that. This is achieved by using `#?#` rule marker. Surprisingly enough, this is actually a useful feature as ExtCSS sometimes is able to hide what regular CSS cannot.
