### ISSUE TITLE
Add $specifichide modifier support

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/SafariConverterLib#6]
https://github.com/AdguardTeam/tsurlfilter/issues/7

@Mizzick can you suggest a way how this modifier can be added?
Can it be added?

**Comment by Mizzick** [comment]
Yeap, I guess it could be, somewhere there we apply exceptions
https://github.com/AdguardTeam/SafariConverterLib/blob/5c462d2da07bee296e24f2e03e60bc782e6424fa/Sources/ContentBlockerConverter/Compiler/Compiler.swift#L161

**Comment by ameshkov** [comment]
Ah, yeah, this is a good idea.

**Comment by ameshkov** [comment]
Or we could use the same approach as with `$badfilter`
