### ISSUE TITLE
The long rule doesn't work

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/SafariConverterLib#9]
This rule (for the ad banner under yandex's search field) doesn't work in Safari extension and AG for iOS (from user rules neither):

`yandex.by,yandex.com,yandex.com.tr,yandex.fr,yandex.kz,yandex.ru,yandex.ua,~afisha.yandex.by,~afisha.yandex.kz,~afisha.yandex.ru,~afisha.yandex.ua,~avia.yandex.by,~avia.yandex.kz,~avia.yandex.ru,~avia.yandex.ua,~bilet.yandex.com.tr,~flights.yandex.com,~disk.yandex.by,~disk.yandex.com,~disk.yandex.com.tr,~disk.yandex.fr,~disk.yandex.kz,~disk.yandex.ru,~disk.yandex.ua,~mail.yandex.by,~mail.yandex.kz,~mail.yandex.ru,~mail.yandex.ua,~mail.yandex.com,~mail.yandex.com.tr,~music.yandex.ru,~music.yandex.ua,~music.yandex.by,~music.yandex.kz,~rabota.yandex.by,~rabota.yandex.kz,~rabota.yandex.ru,~rabota.yandex.ua,~radio.yandex.by,~radio.yandex.kz,~radio.yandex.ru,~radio.yandex.ua,~realty.yandex.by,~realty.yandex.kz,~realty.yandex.ru,~realty.yandex.ua,~tv.yandex.by,~tv.yandex.kz,~tv.yandex.ru,~tv.yandex.ua,~yadi.sk,~zen.yandex.by,~zen.yandex.com,~zen.yandex.kz,~zen.yandex.ru,~zen.yandex.ua,~docviewer.yandex.by,~docviewer.yandex.com,~docviewer.yandex.com.tr,~docviewer.yandex.fr,~docviewer.yandex.kz,~docviewer.yandex.ru,~docviewer.yandex.ua,~rasp.yandex.by,~rasp.yandex.kz,~rasp.yandex.ru,~rasp.yandex.ua##body.i-bem > div.body__wrapper > div.content.i-bem > div.content__informers-bg > div[class] a[data-statlog^="banner"]`

But it works (from user rules) with one domain only:

`yandex.ru##body.i-bem > div.body__wrapper > div.content.i-bem > div.content__informers-bg > div[class] a[data-statlog^="banner"]`

[adg_safari_logs_1617895374305.zip](https://github.com/AdguardTeam/SafariConverterLib/files/6279738/adg_safari_logs_1617895374305.zip)

**Comment by Alex-302** [comment]
probably related to https://github.com/AdguardTeam/SafariConverterLib/issues/8

**Comment by tvinzz** [comment]
unfortunately this rule is not valid for the moment, but this problem will be fixed in #12

**Comment by tvinzz** [comment]
can't be fixed because Safari doesn't support both permitted and restricted domains, so this rule is not valid for Safari.
